<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Regira bv</Authors>
    <RootNamespace>Regira.DAL.PostgreSQL</RootNamespace>
    <PackageId>Regira.DAL.PostgreSQL</PackageId>
    <AssemblyName>Regira.DAL.PostgreSQL</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
    <Version>6.1.3</Version>
    <Description>PostgreSQL data access layer for Regira using Dapper and Npgsql.</Description>
    <PackageTags>regira;dal;postgresql;dapper;npgsql</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.System\Common.System.csproj" />
  </ItemGroup>
</Project>