<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Regira bv</Authors>
    <RootNamespace>Regira.IO.Storage.Azure</RootNamespace>
    <PackageId>Regira.IO.Storage.Azure</PackageId>
    <AssemblyName>Regira.IO.Storage.Azure</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
    <Version>6.0.1</Version>
    <Description>Azure Blob Storage implementation of Regira's IO storage abstractions.</Description>
    <PackageTags>regira;io;storage;azure;blobs</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.IO.Storage\Common.IO.Storage.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
  </ItemGroup>
</Project>